version: '3.1'

services: 

  tor:
    image: dperson/torproxy
    hostname: tor
    container_name: tor
    environment: 
      HOST_HOSTNAME: tor
    ports:
      - 9050:9050
      - 8118:8118
    networks: 
      - scrapper
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - node.name=elasticsearch
    logging: 
        driver: none
    ports:
      - 9201:9200
      - 9301:9300
    networks: 
      - scrapper

  crawler:
    build: 
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler
    links:
      - tor:tor 
    depends_on:
      - tor
    environment: 
      TOR_HOST: tor
      TOR_PORT: 9050
      ALERTS_HOST: 172.31.0.1
      ALERTS_PORT: 3002
    command: ['node', '.']
    ports:
      - 4001:4001
    networks: 
      - scrapper

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    depends_on: 
      - elasticsearch
    environment: 
      ELS_URL: http://172.31.0.1:9201
      CRAWLER_HOST: 172.31.0.1
      CRAWLER_PORT: 4001
      ALERTS_HOST: 172.31.0.1
      ALERTS_PORT: 3002
    ports:
      - 8081:8080
    networks: 
      - scrapper

  alerts: 
    build: 
      context: ./alerts
      dockerfile: Dockerfile
    container_name: alerts
    ports: 
      - 3002:3001
    environment: 
      MONGO_PASS: ${MONGO_PASS}
    networks: 
      - scrapper


volumes:
  elastic_db: 
    driver: local

networks:
  scrapper:
    driver: bridge


    
    

