--- # Stronhold Paste 
  name: "Stronhold Paste"
  url: "http://nzxj65x32vh2fkhk.onion/all"
  network: "tor"
  https: false
  navigation: null 
  pathes: 
    list: section[id=list]
    container: div[class=col-sm-12]
    title: 
      selector: div[class=col-sm-5]
      position: null 
    content: 
      selector: ol
      position: null
    date: 
      selector: div[class=col-sm-6]
      position: 
        start: ' at '
        end: null
    author: 
      selector: div[class=col-sm-6]
      position: 
        start: 10
        end: ' at '

--- # /paste.scratchbook - trending 
name: "paste.scratchbook - Trending"
url: "https://paste.scratchbook.ch/trends"
network: null
https: true
navigation: # if need to navigate to different route
  link: a # element with 'href' property
  relative: false
  inner-container: null
# pagination:
#   container: div[class=pages]
#   unit: a
#   jumps: 1
#   start: 1
pathes: 
  list: tbody
  container: td[class=first]
  title: 
    selector: h1.pagetitle.right
    position: null 
  content: 
    selector: ol
    position: null
  date: 
    selector: div#container > div > div.content > div > div > div > div.meta > span.detail.by
    position: 
      start: ', '
      end: ' ago,'
  author: 
    selector: div#container > div > div.content > div > div > div > div.meta > span.detail.by
    position: 
      start: 'From '
      end: ', '


--- # /paste.scratchbook - recent 
name: "paste.scratchbook - Recent"
url: "https://paste.scratchbook.ch/lists"
network: null
https: true
navigation: # if need to navigate to different route
  link: a # element with 'href' property
  relative: false
  inner-container: null
pathes: 
  list: tbody
  container: td[class=first]
  title: 
    selector: h1.pagetitle.right
    position: null 
  content: 
    selector: ol
    position: null
  date: 
    selector: div#container > div > div.content > div > div > div > div.meta > span.detail.by
    position: 
      start: ', '
      end: ' ago,'
  author: 
    selector: div#container > div > div.content > div > div > div > div.meta > span.detail.by
    position: 
      start: 'From '
      end: ', '


--- # ideone - Recent 
name: "ideone - Recent"
url: "https://ideone.com/recent"
network: null
https: true
navigation: # if need to navigate to different route
  link: a # element with 'href' property
  relative: https://ideone.com
  inner-container: null
pathes: 
  list: div[class=span8]
  container: div[class=source-view]
  title: 
    selector: div#info > legend:nth-child(1)
  content: 
    selector: pre#source > pre > ol
  date: 
    selector: div#solution_date > span
    position: 
      start: null
      end: ago
  author: null
    

--- # /pastebin 
name: "pastebin"
url: "https://pastebin.com/archive"
network: null
https: true
navigation: # if need to navigate to different route
  link: a # element with 'href' property
  relative: https://pastebin.com
  inner-container: null
pathes: 
  list: tbody
  container: tr > td:nth-child(1)
  title: 
    selector: body > div.wrap > div.container > div.content > div.post-view > div.details > div.info-bar > div.info-top > h1
    position: null 
  content: 
    selector: body > div.wrap > div.container > div.content > div.post-view > div.highlighted-code > div.source > ol
    position: null
  date: 
    selector: body > div.wrap > div.container > div.content > div.post-view > div.details > div.info-bar > div.info-bottom > div.date > span
    position: 
      start: null
      end: null
  author: 
    selector: body > div.wrap > div.container > div.content > div.post-view > div.details > div.info-bar > div.info-bottom > div.username > a
    position: 
      start: null
      end: null